# Generated by Django 6.0 on 2025-12-07 19:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(db_index=True, max_length=128)),
                ('customer_name', models.CharField(db_index=True, max_length=255)),
                ('customer_type', models.CharField(blank=True, max_length=128, null=True)),
                ('age', models.IntegerField(blank=True, db_index=True, null=True)),
                ('gender', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('customer_region', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('quantity', models.IntegerField(blank=True, db_index=True, null=True)),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('final_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('product_id', models.CharField(blank=True, max_length=128, null=True)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('product_category', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('brand', models.CharField(blank=True, max_length=128, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list)),
                ('date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('payment_method', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('order_status', models.CharField(blank=True, max_length=128, null=True)),
                ('delivery_type', models.CharField(blank=True, max_length=128, null=True)),
                ('store_id', models.CharField(blank=True, max_length=128, null=True)),
                ('store_location', models.CharField(blank=True, max_length=255, null=True)),
                ('salesperson_id', models.CharField(blank=True, max_length=128, null=True)),
                ('employee_name', models.CharField(blank=True, max_length=255, null=True)),
                ('search_vector', models.TextField(blank=True, editable=False, null=True)),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['date'], name='sales_trans_date_402b02_idx'), models.Index(fields=['quantity'], name='sales_trans_quantit_78f13a_idx'), models.Index(fields=['customer_name'], name='sales_trans_custome_d430da_idx')],
            },
        ),
    ]
