# Generated by Django 6.0 on 2025-12-07 19:07

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        # Enable required PostgreSQL extensions
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS pg_trgm;",
            reverse_sql="DROP EXTENSION IF EXISTS pg_trgm;"
        ),

        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS unaccent;",
            reverse_sql="DROP EXTENSION IF EXISTS unaccent;"
        ),

        # Full-text search GIN index on customer_name + phone_number
        migrations.RunSQL(
            sql="""
            CREATE INDEX IF NOT EXISTS sales_transaction_search_idx
            ON sales_transaction
            USING GIN (
                to_tsvector(
                    'english',
                    coalesce(customer_name, '') || ' ' || coalesce(phone_number, '')
                )
            );
            """,
            reverse_sql="DROP INDEX IF EXISTS sales_transaction_search_idx;"
        ),

        # GIN index on tags ArrayField
        migrations.RunSQL(
            sql="""
            CREATE INDEX IF NOT EXISTS sales_transaction_tags_idx
            ON sales_transaction
            USING GIN (tags);
            """,
            reverse_sql="DROP INDEX IF EXISTS sales_transaction_tags_idx;"
        ),
    ]
